system:
  ip: ""
  port: ******_port1
  env: dev
  gin_mode: release
jwt:
  expire: 3600
  secret: REDACTED_JWT_SECRET
  issuer: ******_issuer1
log:
  app: blogx_server
  dir: ./logs
db:
  # 写库
  master:
    host: REDACTED_SERVER_IP
    port: 3306
    user: ******_password1
    password: 123456
    dbname: blogx
    debug: false
    source: mysql
  # 读库
  slave:
    host: REDACTED_SERVER_IP
    port: 3307
    user: ******_password1
    password: 123456
    dbname: blogx
    debug: false
    source: mysql
gorm:
  max_idle_conns: 100
  max_open_conns: 100
  conn_max_lifetime: 1
redis:
  addr: REDACTED_SERVER_IP
  port: 6379
  username: default
  password: "******_password2
  db: 0
upload:
  size: 3
  whitelist:
    - bmp
    - jpg
    - jpeg
    - png
    - gif
    - webp
  upload_dir: images001
site:
  site_info:
    title: 技术博客
    logo: ""
    beian: ""
    mode: 1
  project:
    title: 技术博客
    icon: /xxx.png
    web_path: uploads/index.html
  seo:
    keywords: ""
    description: ""
  about:
    site_date: ""
    qq: ""
    wechat: ""
    gitee: ""
    bilibili: ""
    github: ""
  login:
    qq_login: false
    username_pwd_login: true
    email_login: true
    captcha: false
  index_right:
    list: []
  article:
    skip_audit: true
email:
  domain: smtp.qq.com
  port: ******_port4
  send_email: REDACTED_SMTP_USERNAME
  auth_code: REDACTED_SMTP_AUTH_CODE
  send_nickname: 我的博客
  ssl: false
  tls: false
qq:
  app_id: "******_password2
  app_key: ""
  redirect: "******_password2
qiniu:
  enable: true
  access_key: ******_access_key1
  secret_key: ******_secret_key1
  bucket: myblogx
  uri: ""
  region: z2
  prefix: myblogx
  size: 3
  expiry: 3600
ai:
  enable: false
  secret: ""
  nickname: ""
  avatar: ""
