system:
  ip: ""
  port: ******_port1
  env: dev
  gin_mode: release
jwt:
  expire: 3600
  secret: ******_secret1
  issuer: ******_issuer1
log:
  app: blogx_server
  dir: ./logs
  level: info
db:
  - host: ******_addr1
    port: ******_port2
    user: admin
    password: ******_password1
    dbname: blogx
    source: mysql
  - host: ******_addr1
    port: ******_port3
    user: admin
    password: ******_password1
    dbname: blogx
    source: mysql
gorm:
  debug: true
  max_idle_conns: 100
  max_open_conns: 100
  conn_max_lifetime: 1
redis:
  addr: ******_addr1
  port: ******_port4
  username: default
  password: ******_password1
  db: 0
kafka:
  mysql:
    brokers:
      - ******_addr1:19092
    topic: blogx-mysql
    group_id: logistics_group
    username: logistics
    password: ******_password2
es:
  addresses:
    - http://******_addr1:9200
  username: elastic
  password: ******_password1
  index: article_index
  addr: ******_addr1:9200
  is_https: false
river:
  enabled: true
  server_id: 1001
  flavor: mysql
  data_dir: ./var
  mysql:
    addr: ******_addr1:******_port2
    user: admin
    password: ******_password1
  source:
    - schema: blogx
      tables:
        - article_models
  rule:
    - schema: blogx
      table: article_models
      index: article_index
      type: _doc
      filter:
        - id
        - created_at
        - updated_at
        - title
        - abstract
        - category_id
        - cover
        - comments_toggle
  charset: "utf8mb4"
  mysqldump: "mysqldump"
  skip_master_data: true
  bulk_size: 128
  flush_bulk_time: 200
upload:
  size: 3
  whitelist:
    - bmp
    - jpg
    - jpeg
    - png
    - gif
    - webp
  upload_dir: images001
site:
  site_info:
    title: 技术博客
    logo: ""
    beian: ""
    mode: 1
  project:
    title: 技术博客
    icon: /xxx.png
    web_path: uploads/index.html
  seo:
    keywords: ""
    description: ""
  about:
    site_date: ""
    qq: ""
    wechat: ""
    gitee: ""
    bilibili: ""
    github: ""
  login:
    qq_login: false
    username_pwd_login: true
    email_login: true
    captcha: false
  index_right:
    list: []
  article:
    skip_examining: true
  comment:
    skip_examining: true
email:
  domain: ******_domain1
  port: ******_port5
  send_email: ******_send_email1
  auth_code: REDACTED_SMTP_AUTH_CODE
  send_nickname: 我的博客
  ssl: false
  tls: false
qq:
  app_id: "123456"
  app_key: ""
  redirect: "123456"
qiniu:
  enable: true
  access_key: ******_access_key1
  secret_key: ******_secret_key1
  bucket: myblogx
  uri: ""
  region: z2
  prefix: myblogx
  size: 0
  expiry: 0
ai:
  enable: true
  secret: "******_secret2
  base_url: "******_base_url1
  chat_model: "gpt-3.5-turbo"
  reason_model: ""
  timeout_sec:
  max_input_chars:
  temperature:
  daily_quota:
  nickname: ""
  avatar: ""
