user  root;
worker_processes  1;

events {
    worker_connections  1024;
}

http {
  gzip on;
  gzip_static on;
  gzip_min_length  5k;
  gzip_buffers     4 16k;
  gzip_http_version 1.0;
  gzip_comp_level 7;
  gzip_types       text/plain application/javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png;
  gzip_vary on;

  include       mime.types;
  default_type  application/octet-stream;

  access_log  /var/log/nginx/access.log;
  error_log  /var/log/nginx/error.log;

  sendfile        on;
  #tcp_nopush     on;

  #keepalive_timeout  0;
  keepalive_timeout  500;

  #gzip  on;
  client_max_body_size 2000m;
  ssl_certificate /usr/share/nginx/cert/domain.pem;
  ssl_certificate_key /usr/share/nginx/cert/domain.key;

  server {
     listen       80;
     listen    443 ssl;
     server_name REDACTED_SITE_DOMAIN;
     # rewrite ^(.*)$ https://$host:443$1 permanent;

     location / {
       try_files $uri $uri/ /index.html;
       root   /usr/share/nginx/fai_web;
       index  index.html;
     }

     location /api/ {
        # 将客户端请求的 Host 头（域名/端口）转发给后端服务器
        proxy_set_header Host $host;
        # 传递真实客户端，让后端能获取实际请求 IP，而非 Nginx 服务器的 IP
        proxy_set_header X-Real-IP $remote_addr;
        # 自定义请求头：和 X-Real-IP 作用类似，部分后端框架会读取 REMOTE-HOST 获取客户端 IP
        proxy_set_header REMOTE-HOST $remote_addr;
        # 核心反向代理，将当前请求转发到后端的这个地址
        proxy_pass http://10.2.0.7:8080/api/;
     }

     location /api/ai/article {
       proxy_set_header Host $host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header REMOTE-HOST $remote_addr;
       proxy_pass http://10.2.0.7:8080/api/chat/sse;
       proxy_set_header Connection "";
       proxy_http_version 1.1;
       proxy_buffering off;
       proxy_cache off;
     }

      location /api/chat/ws {
           proxy_pass http://10.2.0.7:8080/;
           proxy_http_version 1.1;
           proxy_set_header Upgrade $http_upgrade;
           proxy_set_header Connection "upgrade";
           proxy_redirect off;
           proxy_set_header REMOTE-HOST $remote_addr;
           proxy_set_header Host $host;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
           proxy_set_header X-Forwarded-Host $server_name;
           proxy_read_timeout 3600s;
     }
  }
}